2020-02-19 13:06:23,952 ERROR: Exception on /reportMenu/11/ [GET] [in c:\Users\richa\OneDrive\Projects\AzureCertification\venv\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "c:\Users\richa\OneDrive\Projects\AzureCertification\venv\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\Users\richa\OneDrive\Projects\AzureCertification\venv\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\Users\richa\OneDrive\Projects\AzureCertification\venv\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\Users\richa\OneDrive\Projects\AzureCertification\venv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "c:\Users\richa\OneDrive\Projects\AzureCertification\venv\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\richa\OneDrive\Projects\AzureCertification\venv\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\Users\richa\OneDrive\Projects\AzureCertification\app\routes.py", line 820, in reportMenu
    return render_template('reports.html',  trainingDatesShop1=trainingDatesShop1)
NameError: name 'trainingDatesShop1' is not defined
2020-02-19 13:17:22,996 INFO: Certification startup [in c:\Users\richa\OneDrive\Projects\AzureCertification\app\__init__.py:48]
2020-02-19 13:17:59,123 ERROR: Exception on /reportMenu/11/ [GET] [in c:\Users\richa\OneDrive\Projects\AzureCertification\venv\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "c:\Users\richa\OneDrive\Projects\AzureCertification\venv\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\Users\richa\OneDrive\Projects\AzureCertification\venv\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\Users\richa\OneDrive\Projects\AzureCertification\venv\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\Users\richa\OneDrive\Projects\AzureCertification\venv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "c:\Users\richa\OneDrive\Projects\AzureCertification\venv\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\richa\OneDrive\Projects\AzureCertification\venv\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\Users\richa\OneDrive\Projects\AzureCertification\app\routes.py", line 820, in reportMenu
    return render_template('reportMenu.html',shopName=shopName,trainingDate=t.trainingDate)
NameError: name 'shopName' is not defined
2020-02-19 13:18:49,103 INFO: Certification startup [in c:\Users\richa\OneDrive\Projects\AzureCertification\app\__init__.py:48]
2020-02-19 14:42:14,930 INFO: Certification startup [in c:\Users\richa\OneDrive\Projects\AzureCertification\app\__init__.py:48]
2020-02-19 14:43:27,549 INFO: Certification startup [in c:\Users\richa\OneDrive\Projects\AzureCertification\app\__init__.py:48]
2020-02-19 14:44:04,721 ERROR: Exception on /reportMenu/11/ [GET] [in c:\Users\richa\OneDrive\Projects\AzureCertification\venv\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "c:\Users\richa\OneDrive\Projects\AzureCertification\venv\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\Users\richa\OneDrive\Projects\AzureCertification\venv\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\Users\richa\OneDrive\Projects\AzureCertification\venv\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\Users\richa\OneDrive\Projects\AzureCertification\venv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "c:\Users\richa\OneDrive\Projects\AzureCertification\venv\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\richa\OneDrive\Projects\AzureCertification\venv\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\Users\richa\OneDrive\Projects\AzureCertification\app\routes.py", line 822, in reportMenu
    shopName= db.session.query(ShopName.Shop_Name).filter(Shop_Name.Shop_Number == shopNumber).scalar()
NameError: name 'Shop_Name' is not defined
2020-02-19 14:45:13,059 INFO: Certification startup [in c:\Users\richa\OneDrive\Projects\AzureCertification\app\__init__.py:48]
2020-02-19 14:54:19,031 INFO: Certification startup [in c:\Users\richa\OneDrive\Projects\AzureCertification\app\__init__.py:48]
2020-02-19 15:22:51,206 INFO: Certification startup [in c:\Users\richa\OneDrive\Projects\AzureCertification\app\__init__.py:48]
2020-02-19 15:30:19,130 INFO: Certification startup [in c:\Users\richa\OneDrive\Projects\AzureCertification\app\__init__.py:48]
2020-02-19 15:32:28,589 INFO: Certification startup [in c:\Users\richa\OneDrive\Projects\AzureCertification\app\__init__.py:48]
2020-02-19 15:40:14,919 INFO: Certification startup [in c:\Users\richa\OneDrive\Projects\AzureCertification\app\__init__.py:48]
2020-02-19 15:41:47,152 INFO: Certification startup [in c:\Users\richa\OneDrive\Projects\AzureCertification\app\__init__.py:48]
2020-02-19 15:43:34,984 INFO: Certification startup [in c:\Users\richa\OneDrive\Projects\AzureCertification\app\__init__.py:48]
2020-02-19 15:43:53,380 ERROR: Exception on /reportMenu/10/ [GET] [in c:\Users\richa\OneDrive\Projects\AzureCertification\venv\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "c:\Users\richa\OneDrive\Projects\AzureCertification\venv\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\Users\richa\OneDrive\Projects\AzureCertification\venv\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\Users\richa\OneDrive\Projects\AzureCertification\venv\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\Users\richa\OneDrive\Projects\AzureCertification\venv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "c:\Users\richa\OneDrive\Projects\AzureCertification\venv\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\richa\OneDrive\Projects\AzureCertification\venv\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\Users\richa\OneDrive\Projects\AzureCertification\app\routes.py", line 824, in reportMenu
    return render_template('reportMenu.html',shopName=shopName,headingDate=headingDate,trainingDate=t.trainingDate,trainingDateID=id,shopNumber=shopNumber)
  File "c:\Users\richa\OneDrive\Projects\AzureCertification\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\Users\richa\OneDrive\Projects\AzureCertification\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\Users\richa\OneDrive\Projects\AzureCertification\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\Users\richa\OneDrive\Projects\AzureCertification\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\Users\richa\OneDrive\Projects\AzureCertification\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\Users\richa\OneDrive\Projects\AzureCertification\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "c:\Users\richa\OneDrive\Projects\AzureCertification\app\templates\reportMenu.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "c:\Users\richa\OneDrive\Projects\AzureCertification\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\Users\richa\OneDrive\Projects\AzureCertification\app\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\Users\richa\OneDrive\Projects\AzureCertification\app\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\Users\richa\OneDrive\Projects\AzureCertification\app\templates\bootstrap\base.html", line 33, in block "html"
    {% block body -%}
  File "c:\Users\richa\OneDrive\Projects\AzureCertification\app\templates\bootstrap\base.html", line 36, in block "body"
    {% block content -%}
  File "c:\Users\richa\OneDrive\Projects\AzureCertification\app\templates\base.html", line 118, in block "content"
    {% block app_content %}{% endblock %}
  File "c:\Users\richa\OneDrive\Projects\AzureCertification\app\templates\reportMenu.html", line 8, in block "app_content"
    <li><a href="rptNotCertified/{{t1.shopNumber}}">Not Certified</a></li>
  File "c:\Users\richa\OneDrive\Projects\AzureCertification\venv\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 't1' is undefined
2020-02-19 15:44:43,274 INFO: Certification startup [in c:\Users\richa\OneDrive\Projects\AzureCertification\app\__init__.py:48]
2020-02-19 15:46:32,573 INFO: Certification startup [in c:\Users\richa\OneDrive\Projects\AzureCertification\app\__init__.py:48]
